### ISSUE TITLE
Special characters in the .env

### ISSUE THREAD

**Issue by frogeth** [Layr-Labs/eigenda-operator-setup#24]
My password for my ECDSA and BLS key had a special character inside. I would opt into EigenDA using ./run.sh opt-in and the password would decrypt properly, but when i would docker compose up i would get the following error:

`application failed: could not decrypt the ECDSA file: /app/operator_keys/ecdsa_key.json`

The temporary solution at the moment is to leave it as is for the opt-in/opt-out command (without single quotes) and before docker composing up or down I would add single quotes to the .env

Special characters include: ?,! and maybe a few others thats just what i know of. 

The solution imo is to just allow the opt-in/opt-out command to support a password with single quotes as to not confuse people onboarding.

**Comment by eferbarn** [comment]
The situation gets really bad when there's a parenthesis in the password variable.
In that case, even the temporary solution mentioned doesn't work, and repeatedly displays the following error message:
`‍‍./run.sh: 91: ./.env: Syntax error: "(" unexpected`

**Comment by shrimalmadhur** [comment]
Thanks for reporting this issue. I will try to look into what is happening. I am wondering if there's an issue with how `docker-compose` file reads the password with parentheses.

**Comment by shrimalmadhur** [comment]
Have you tried single quotes around password with special characters? Looking at this issue - https://github.com/docker/compose/issues/8607 
maybe worth trying and see if it resolves. I will also try on my side when I have some cycles.
