### ISSUE TITLE
Failed to read or decrypt the BLS private key

### ISSUE THREAD

**Issue by hosseinnedaee** [Layr-Labs/eigenda-operator-setup#25]
when I run `./run.sh` it gives me this error:
`Error: failed to read or decrypt the BLS private key: open /root/.eigenlayer/operator_keys/my.bls.key.json: no such file or directory`
the file in the provided path really exists.

**Comment by shrimalmadhur** [comment]
@hosseinnedaee is this resolved. do you need any further help?

**Comment by hosseinnedaee** [comment]
I created a new user account and repeated the steps from the beginning, which successfully resolved the issue.
