### ISSUE TITLE
The problem with parentheses in the password (Special characters) is very severe

### ISSUE THREAD

**Issue by eferbarn** [Layr-Labs/eigenda-operator-setup#28]
We have talked about the problem with [frogeth](https://github.com/frogeth) in [this issue](https://github.com/Layr-Labs/eigenda-operator-setup/issues/24).
I've tried almost everything to resolve it. The issue with parentheses seems to be a severe problem.

I also tried this trick:
```
PARENTHESIS="("
NODE_ECDSA_KEY_PASSWORD=something${PARENTHESIS}
NODE_BLS_KEY_PASSWORD=something${PARENTHESIS}else
```

test.sh:
```
. ./.env
echo $NODE_ECDSA_KEY_PASSWORD
```

```
$ chmod +x test.sh
$ ./test.sh
something(
```

Everything seems ok, but the problem is still there.
`Error: failed to read or decrypt the BLS private key: could not decrypt key with the given password`

[Message on Discord](https://discord.com/channels/1089434273720832071/1089792679254163497/1186686546963869806)

![Problem](https://github.com/Layr-Labs/eigenda-operator-setup/assets/90908412/dbf6779b-82c8-4a4e-8802-c127ef55820d)

```[tasklist]
### Tasks
```

**Comment by shrimalmadhur** [comment]
Thanks for reporting this issue. I will try to look into what is happening. I am wondering if there's an issue with how `docker-compose` file reads the password with parentheses and try to find this issue out.

**Comment by shrimalmadhur** [comment]
@eferbarn Have you tried single quotes around password with special characters? Looking at this issue - https://github.com/docker/compose/issues/8607 
maybe worth trying and see if it resolves. I will also try on my side when I have some cycles.

**Comment by eferbarn** [comment]
Yes! I tried lots of solutions. They didn't work at all! Assume that my password is `blah(blah`!
I tried all of these potential solutions:
* `"blah(blah"`
* `'blah(blah'`
* `blah\(blah`

Finally, I just used these commands to change my passwords:
1. `$ cd .eigenlayer/operator_keys`
2. `$ rm <keyname>.bls.key.json`
3. `$ rm <keyname>.ecdsa.key.json`
4. `$ ./eigenlayer operator keys import --key-type ecdsa <name> <ecdsa_private_key>`
5. `$ ./eigenlayer operator keys import --key-type bls <name> <bls_private_key>`

**Comment by shrimalmadhur** [comment]
Thanks for checking. this is weird. I will dig deeper into it as I think it's important to support any passwords.
