### ISSUE TITLE
Quorum is overfilled

### ISSUE THREAD

**Issue by FandyyyDev** [Layr-Labs/eigenda-operator-setup#32]
I completed all the steps, but when I run the "./run.sh opt-in" command, I receive the following error.

     ERROR   logging/zap_logger.go:97        Unable to register operator with avs registry coordinator
github.com/Layr-Labs/eigensdk-go/logging.(*ZapLogger).Errorf
        /go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.0.8/logging/zap_logger.go:97
github.com/mangata-finance/eigen-layer-monorepo/operator.(*Operator).RegisterOperatorWithAvs
        /app/operator/registration.go:29
github.com/mangata-finance/eigen-layer-monorepo/operator/plugin/actions.RegisterOperatorWithAvs
        /app/operator/plugin/actions/register_operator_with_avs.go:28
github.com/urfave/cli.HandleAction
        /go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:524
github.com/urfave/cli.Command.Run
        /go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:175
github.com/urfave/cli.(*App).Run
        /go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:277
main.main
        /app/operator/plugin/cmd/main.go:37
runtime.main
        /usr/local/go/src/runtime/proc.go:267
2024/01/06 15:12:21 execution reverted: BLSRegistryCoordinatorWithIndices._registerOperatorWithCoordinatorAndNoOverfilledQuorums: quorum is overfilled

I checked all the steps one by one and I couldn't see anything wrong. What is the solution to this? Is there anyone who can help?

**Comment by shrimalmadhur** [comment]
Hi, I am not sure why you are using a forked version `github.com/mangata-finance/eigen-layer-monorepo` - it's hard to help when we don't know what code you are running. If you are able to share the code you are running, I can help you.

**Comment by shrimalmadhur** [comment]
closing this as I see no response. Please re-open if this is still an issue.
