### ISSUE TITLE
The node is not opt-in to EigenDA yet!

### ISSUE THREAD

**Issue by eferbarn** [Layr-Labs/eigenda-operator-setup#33]
After upgrading to the latest version, I see the following message in my logs of operator!

```
The node has successfully started. Note it's not opt-in to EigenDA yet (it's not receiving or validating data in EigenDA). To register, please follow the EigenDA operator guide section in docs.eigenlayer.xyz caller=node.go:183
```

I ran `./run.sh opt-in` before `docker compose up -d` and received `successfully opt-in the EigenDA, for operator ID: ***`!

**Comment by shrimalmadhur** [comment]
I don't think so you are running the updated version `v0.2.0` yet. this log message is for older version - https://github.com/Layr-Labs/eigenda/commit/ee891cad9a5a93e4206aa078e8eaf147db30fedf

**Comment by eferbarn** [comment]
I am running the latest version! My operator also returns signatures, but at the top of the logs file, I see the mentioned warning message!

**Comment by shrimalmadhur** [comment]
Hmm this is strange. The logs is from old binary. Since you are validating blobs, you are good. but I will take a note and see what is going on.

**Comment by eferbarn** [comment]
A big shout out to you, @shrimalmadhur! I am truly grateful for your support!

After I realized that the operator had been ejected from AVS (that was unexpected because everything was under control and the operator was returning signatures using v0.2.0) I restarted everything again. Now, I see the correct logs from the latest binary. (Commit: [ee891ca...fedf](https://github.com/Layr-Labs/eigenda/commit/ee891cad9a5a93e4206aa078e8eaf147db30fedf))

`The node has successfully started. Note: if it's not opted in on https://goerli.eigenlayer.xyz/avs/eigenda, then please follow the EigenDA operator guide section in docs.eigenlayer.xyz to register caller=logging.go:65`

Anyway, IDK why my operator has been ejected despite returning the correct logs and hashes! I have pieces of evidence to prove that!

**Comment by shrimalmadhur** [comment]
Thank you! I don't know what happened with logs. Maybe docker had some glitch. I don't see you anymore in our non-signer list so you are good - could be an oversight on our side. I am closing this issue for now. Feel free to create new one with any other issues.
