### ISSUE TITLE
EigenDA TVL in top 200 but getting "Complete an Error cycle...." in logs constantly and not signing batches

### ISSUE THREAD

**Issue by spidey-169** [Layr-Labs/eigenda-operator-setup#39]
Hi,

My EigenDA operator is currently not signing blocks, and only showing the "Complete an Error Cycle...." message in the logs. I have registered my operator, delegated to it from another address and ensured that my .env file has the correct parameters. 

https://goerli.eigenlayer.xyz/operator/0x866a3529d9d6abc8d0d73433fcf0926105727c07

I used the official docs to setup my DA, and using Ubuntu 22.04, 1TB HDD, 8GB Ram adn 4 CPU

This is the screenshot confirming operator registration and details

<img width="872" alt="Screen Shot 2024-01-15 at 11 43 20 PM" src="https://github.com/Layr-Labs/eigenda-operator-setup/assets/83369878/1ca1db74-6f82-415d-bc22-87191429f963">

When I start my EigenDA, it immediately starts giving me the error message ""Complete an Error Cycle...." as shown here

<img width="1323" alt="Screen Shot 2024-01-15 at 11 25 44 PM" src="https://github.com/Layr-Labs/eigenda-operator-setup/assets/83369878/da84d59b-f8a6-420f-ad35-1dbd9a49bd76">

I have ensured that the BLS,ECDSA key paths are correct and same in both .env and docker_compose.yml and I am using 0.2.1 release

This is the screenshot confirming it successfully opted in
<img width="1348" alt="Screen Shot 2024-01-15 at 11 20 50 PM" src="https://github.com/Layr-Labs/eigenda-operator-setup/assets/83369878/e9e8e4c5-631a-4d5f-b7f3-67cacdaae5c3">

Here are the settings for my .env file 
<img width="904" alt="Screen Shot 2024-01-15 at 11 10 37 PM" src="https://github.com/Layr-Labs/eigenda-operator-setup/assets/83369878/697cc929-57cd-4eb1-81c3-142f4aad998c">

My DA can't seem to get outside the "Complete an Error cycle...." message log, and I have tried restaerting node, Opting-again and Recreating docker containers too. 

I have also sent a message in the support link, but wanted to open an issue as I saw a few other folks facing the same issue.

**Comment by acomg** [comment]
Did you enter your IP in [NODE_HOSTNAME]?

**Comment by shrimalmadhur** [comment]
> I am using 'localhost' currently. Should that be an issue? I have confirmed with a few others that should be fine

Yes. It should be a publicly available IP. although the node software already updated it if you see the screenshot `88.99.3.143`. Is this a public IP? If our disperser cannot reach it on port `32005` you won't be able to receive traffic.

**Comment by spidey-169** [comment]
> > I am using 'localhost' currently. Should that be an issue? I have confirmed with a few others that should be fine
> 
> Yes. It should be a publicly available IP. although the node software already updated it if you see the screenshot `88.99.3.143`. Is this a public IP? If our disperser cannot reach it on port `32005` you won't be able to receive traffic.

Its a public IP, and I have switched off firewall now, and checked that ports 32004 and 32005 both are accessible from outside

**Comment by spidey-169** [comment]
> > I am using 'localhost' currently. Should that be an issue? I have confirmed with a few others that should be fine
> 
> Yes. It should be a publicly available IP. although the node software already updated it if you see the screenshot `88.99.3.143`. Is this a public IP? If our disperser cannot reach it on port `32005` you won't be able to receive traffic.

It works now, I think for some reason 32004 wasn't accessible and that was causing the issue. Thanks for resolving the issue.

**Comment by spidey-169** [comment]
Issue solved. Thanks
