### ISSUE TITLE
operatorID Rate Limit Exceeded

### ISSUE THREAD

**Issue by swjung703** [Layr-Labs/eigenda-operator-setup#60]
When I run
`./run.sh opt-in`

Error occured like below.
error: failed to request churn approval: rpc error: code = Unknown desc = rate limiter error: operatorID Rate Limit Exceeded:

I'm first time running node.
I don't know why ma Rate Limit Exceeded.

**Comment by shrimalmadhur** [comment]
this is intentional so that we don't overwhelm our churner. please wait for 5 min before executing again.

**Comment by swjung703** [comment]
> this is intentional so that we don't overwhelm our churner. please wait for 5 min before executing again.

Thank you. I'll try later.

**Comment by shrimalmadhur** [comment]
closing this. please re-open if this issue exist or if there's any other issue.
