### ISSUE TITLE
Failed to read or decrypt the BLS private key

### ISSUE THREAD

**Issue by sportmug** [Layr-Labs/eigenda-operator-setup#65]
This is similar to a Closed Issue but when running ./run.sh opt-in I'm getting the following error:

Error: failed to read or decrypt the BLS private key: read /app/operator_keys/bls_key.json: is a directory

**Comment by shrimalmadhur** [comment]
this is possible if you did not provide correct path to bls key in `.env` file. Please provide full path correctly. Please re-open if it's still an issue
