### ISSUE TITLE
Make 20 eth TVL requirement In order to opt-in into EigenDA as an Operator

### ISSUE THREAD

**Issue by wnhedaxx** [Layr-Labs/eigenda-operator-setup#67]
As per your docs  In order to opt-in into EigenDA as an Operator, we must meet the following delegated TVL requirements:

Have a minimum of 32 ETH delegated....

Think about it and make it minimum of 20 ETH delegated..

**Comment by wnhedaxx** [comment]
@shrimalmadhur 
Look

**Comment by shrimalmadhur** [comment]
There is no hard requirement on minimum ETH for opting into EigenDA. Right now we have 200 operators and minimum required would be based on how much the minimum operators has delegated to them. Where do you see that minimum requirement? @wnhedaxx

**Comment by wnhedaxx** [comment]
![Screenshot_2024-02-26-09-50-52-488_com android chrome](https://github.com/Layr-Labs/eigenda-operator-setup/assets/70830772/2153f748-53c7-4d82-bdce-997ba383d8c9)
I haven't tried yet...
I only checked your docs 
Here is the screenshot what i have seen
@shrimalmadhur

**Comment by shrimalmadhur** [comment]
I will check but 32 might come from Native restaking since - to run a ETH validator minimum is 32 ETH. 20 anyway doesn't make sense. We will update the docs. Anyway this issue is not relevant since 20 ETH can not be made in any case. so closing this :)
