### ISSUE TITLE
An error occurred while transitioning from Goerli to Holesky

### ISSUE THREAD

**Issue by nod3dev** [Layr-Labs/eigenda-operator-setup#79]
Hello, I'm Danny from NOD3

### Issue Summary
.   
  

Conflicts occurred while moving from the Goerli testnet to the Holesky testnet. An error emerged while proceeding after deleting everything except ECDSA, BLS, and Bin. Please check the photo. I have resolved this issue by reinstalling the server and then using the imported ECDSA and BLS keys. In my opinion, it seems there might be an issue with either the ECDSA, BLS keys, or the Bin.
Additionally, I used the Holesky RPC from this link.(https://chainlist.org/chain/17000)

![error](https://github.com/Layr-Labs/eigenda-operator-setup/assets/156356642/0af34620-587d-4ab6-a319-76c3690af16e)

### Environment
. 

- EigenDA version: holesky
- Operating System: Ubuntu 22.02
- Node configuration (if applicable): 
- Any specific settings or modifications:

### Steps to Reproduce

1. rm -rf eigenlayer metadata.json operator.yaml
2. git clone https://github.com/Layr-Labs/eigenlayer-cli.git
cd eigenlayer-cli
mkdir -p build
go build -o build/eigenlayer cmd/eigenlayer/main.go
3. eigenlayer operator config create
4. eigenlayer operator register operator.yaml
error

### Actual Behavior
. 

### Possible Solution
. 

After reinstalling the server, start the installation from the beginning

### Additional Context
.

**Comment by shrimalmadhur** [comment]
please open issue in https://github.com/Layr-Labs/eigenlayer-cli/issues for this. thanks
