### ISSUE TITLE
No "el_slasher_address" and "bls_public_key_compendium_address" were provided by the team

### ISSUE THREAD

**Issue by eferbarn** [Layr-Labs/eigenda-operator-setup#83]
### Issue Summary
I was considering the transition from the Goerli network to the Holesky network.

```env
el_slasher_address=[slasher_address]
bls_public_key_compendium_address=[bpkc_address]
```

These two essential parameters in the `operator.yaml` file, which were supposed to be provided by the team are not included in the official documentation, and this has caused container execution to face issues. In fact, those who managed to register have used corresponding contracts in the Guerli network, leading to many operators being registered, but unable to return signatures.
#### [Official Doc URL](https://docs.eigenlayer.xyz/eigenlayer/operator-guides/operator-installation#holesky-smart-contract-addresses)
---
### Environment 
- Eigenlayer CLI version: 0.6.3
- Operating System: Ubuntu 22.04
---
### Expected Behavior
The `eigenlayer operator register operator.yaml` command should execute without any issues.

### Actual Behavior
Thrown error: `Failed to fetch Slasher address: no contract code at given address` when trying to register in EigenLayer.

**Comment by shrimalmadhur** [comment]
the new cli required `el_delegation_manager_address` Please open issue in https://github.com/Layr-Labs/eigenlayer-cli/issues for any cli related issues.
